// <auto-generated />
using BestiaryDB.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BestiaryDB.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230114094450_BestiaryCreate")]
    partial class BestiaryCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.GameModel.Entity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArmorClass")
                        .HasColumnType("int");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("int");

                    b.Property<int>("AttacksPerRound")
                        .HasColumnType("int");

                    b.Property<int>("DamageDiceThrowsNumber")
                        .HasColumnType("int");

                    b.Property<int>("DamageDiceType")
                        .HasColumnType("int");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("int");

                    b.Property<int>("HP")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Entities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArmorClass = 10,
                            AttackModifier = 3,
                            AttacksPerRound = 1,
                            DamageDiceThrowsNumber = 6,
                            DamageDiceType = 8,
                            DamageModifier = 6,
                            HP = 33,
                            Name = "Firenewt warlock of Imix"
                        },
                        new
                        {
                            Id = 2,
                            ArmorClass = 12,
                            AttackModifier = 0,
                            AttacksPerRound = 4,
                            DamageDiceThrowsNumber = 1,
                            DamageDiceType = 8,
                            DamageModifier = 2,
                            HP = 24,
                            Name = "Swarm of ravens"
                        },
                        new
                        {
                            Id = 3,
                            ArmorClass = 12,
                            AttackModifier = 2,
                            AttacksPerRound = 1,
                            DamageDiceThrowsNumber = 8,
                            DamageDiceType = 12,
                            DamageModifier = 8,
                            HP = 60,
                            Name = "Enormous Tentacle"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
